name: eye_vision
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  bottom_animation: ^2.0.0
  bottom_navy_bar: ^5.6.0
  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.1
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.1.0
  provider: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Arvo
      fonts:
        - asset: Fonts/Arvo-Bold.ttf
    - family: Playfair Display SC
      fonts:
        - asset: Fonts/PlayfairDisplaySC-Black.ttf
  assets:
    - assets/images/
    - assets/data/
